before_install:
- sudo apt-get update && sudo apt-get install texlive-latex-base
script:
- pdflatex tr2.tex
- bibtex paper
- pdflatex tr2.tex
- pdflatex tr2.tex
- if [ "$TRAVIS_BRANCH" == "master" ]; then bash ./deploy.sh; fi
env:
  global:
  - GH_REF: github.com:doctor-g/tr2.git 